### ISSUE TITLE
Title and CSS in titlepage image and cover image

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/khalil-gibran_the-forerunner-his-parables-and-poems#2]
In cover.svg and titlepage.svg, please change the `<title>` tag to exclude the subtitle, as we only include subtitles in metadata and half title pages. Also note that the CSS formatting got messed up by `clean`. (This bug is already fixed in `clean`.) Can you reformat the CSS to match what the the template formatting looks like? Make sure to run `build-images` again after making these changes.

**Comment by samisiddiqui** [comment]
Resolved as of https://github.com/samisiddiqui/khalil-gibran_the-forerunner-his-parables-and-poems/commit/12d2f28bf76a7858b6980852daa5adc8b4f4a792
