### ISSUE TITLE
ToC issues

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/khalil-gibran_the-forerunner-his-parables-and-poems#3]
- In landmarks, The Forerunner is marked as frontmatter but it should be bodymatter

**Comment by samisiddiqui** [comment]
Resolved as of https://github.com/samisiddiqui/khalil-gibran_the-forerunner-his-parables-and-poems/commit/1db65f384e02ce4f7e7093ef44e5cf7b687f0089
