### ISSUE TITLE
Colophon issues

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/khalil-gibran_the-forerunner-his-parables-and-poems#4]
- Remove subtitle from first line
- SE link is incorrect at the bottom; should not have subtitle and should match identifier in content.opf

**Comment by samisiddiqui** [comment]
Resolved as of https://github.com/samisiddiqui/khalil-gibran_the-forerunner-his-parables-and-poems/commit/818f6a350d89ec25b5523766f2dbbdbc9c986248
