### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/khalil-gibran_the-forerunner-his-parables-and-poems#5]
The King Hermit

- Miscurled ending quotes in sentence ending in "bathes thrice a day"

"Said a Sheet of Snow-White Paper …"

- Use double quotes in title. Remember to change ToC, title tag, and h2 tag.

Content.opf

- Missing closing `<p>` tag in long description
- Missing MFR and PGDP as transcribers in metadata

**Comment by samisiddiqui** [comment]
Fixed as of https://github.com/samisiddiqui/khalil-gibran_the-forerunner-his-parables-and-poems/commit/212fdb3ae0af09a073e845a02546b54489444ac3
